channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=26.0.1
- pip:
  - mlflow==2.22.4
  - cloudpickle==3.1.2
  - numpy==2.3.4
  - pandas==2.3.3
  - psutil==7.2.0
  - pyarrow==19.0.1
  - scikit-learn==1.7.2
  - scipy==1.16.0
name: mlflow-env
